//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinAction.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PinAction.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 It seems {0} is not a branch reference either... skipping {1} 的本地化字符串。
        /// </summary>
        internal static string ErrorBranchNotFound {
            get {
                return ResourceManager.GetString("ErrorBranchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to get hash:  的本地化字符串。
        /// </summary>
        internal static string ErrorGetHashFailed {
            get {
                return ResourceManager.GetString("ErrorGetHashFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified path {0} does not exist. 的本地化字符串。
        /// </summary>
        internal static string ErrorPathNotExist {
            get {
                return ResourceManager.GetString("ErrorPathNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The GitHub API rate limit has been exceeded, please try again later. 的本地化字符串。
        /// </summary>
        internal static string ErrorRateLimitExceeded {
            get {
                return ResourceManager.GetString("ErrorRateLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The repository {0} does not exist. 的本地化字符串。
        /// </summary>
        internal static string ErrorRepositoryNotExist {
            get {
                return ResourceManager.GetString("ErrorRepositoryNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tag {0} not found, maybe this is a branch reference? I&apos;ll give it a try... 的本地化字符串。
        /// </summary>
        internal static string ErrorTagNotFound {
            get {
                return ResourceManager.GetString("ErrorTagNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found [blue]{1}[/] in [blue]{0}[/] 的本地化字符串。
        /// </summary>
        internal static string FindAction {
            get {
                return ResourceManager.GetString("FindAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Usage: pinaction &lt;dir/file&gt; 的本地化字符串。
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can pass multiple files or directories at once. 的本地化字符串。
        /// </summary>
        internal static string HelpLine1 {
            get {
                return ResourceManager.GetString("HelpLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For directories, it will recursively look for `.yaml` or `.yml` files within. 的本地化字符串。
        /// </summary>
        internal static string HelpLine2 {
            get {
                return ResourceManager.GetString("HelpLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show this help message 的本地化字符串。
        /// </summary>
        internal static string HelpShowHelp {
            get {
                return ResourceManager.GetString("HelpShowHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show license 的本地化字符串。
        /// </summary>
        internal static string HelpShowLicense {
            get {
                return ResourceManager.GetString("HelpShowLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show version 的本地化字符串。
        /// </summary>
        internal static string HelpShowVersion {
            get {
                return ResourceManager.GetString("HelpShowVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run the [blue]pinaction license[/] command for license information. 的本地化字符串。
        /// </summary>
        internal static string HelpVer2License {
            get {
                return ResourceManager.GetString("HelpVer2License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 License 的本地化字符串。
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Package 的本地化字符串。
        /// </summary>
        internal static string Package {
            get {
                return ResourceManager.GetString("Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pinned 的本地化字符串。
        /// </summary>
        internal static string Pinned {
            get {
                return ResourceManager.GetString("Pinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skipping {0} because it is already pinned to the full-length hash. 的本地化字符串。
        /// </summary>
        internal static string SkippingAlreadyPinnedHashes {
            get {
                return ResourceManager.GetString("SkippingAlreadyPinnedHashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 version 的本地化字符串。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pin Action 的本地化字符串。
        /// </summary>
        internal static string VersionTableTitle {
            get {
                return ResourceManager.GetString("VersionTableTitle", resourceCulture);
            }
        }
    }
}
