name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 版本号 (不带v)
        required: true
        default: 2.3.3
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    env:
      PYTHONIOENCODING: utf-8

    steps:
      - name: 检出代码
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: 设置 .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: 10.x

      - name: 配置 Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.x

      - name: 更新版本号
        shell: bash
        env:
          GITHUB_EVENT_INPUTS_VERSION: ${{ github.event.inputs.version }}
        run: |-
          if [[ "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]]; then
            version="${GITHUB_EVENT_INPUTS_VERSION#v}"
          else
            version="${GITHUB_REF_NAME#refs/tags/}"
            version="${version#v}"
          fi
          
          python ".scripts/update_version.py" "$version"

      - name: 发布
        run: dotnet publish PinAction --configuration Release

      - name: 打包安装程序
        shell: pwsh
        run: |-
          Write-Host "通过 GitHub API 下载中文翻译..."
          $apiUrl = "https://api.github.com/repos/jrsoftware/issrc/contents/Files/Languages/ChineseSimplified.isl?ref=main"
          $downloadPath = "C:\Program Files (x86)\Inno Setup 6\Languages\ChineseSimplified.isl"
          Invoke-WebRequest -Uri $apiUrl -Headers @{ "Accept" = "application/vnd.github.raw+json" } -OutFile $downloadPath
          Get-FileHash -Path $downloadPath -Algorithm SHA256

          iscc installer.iss

      - name: 上传构建文件
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: Release/PinAction_Setup.exe

      - name: 发布至发行版
        env:
          GH_TOKEN: ${{ github.token }}
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: gh release upload "$env:GITHUB_REF_NAME" "Release/PinAction_Setup.exe" --clobber
